### ISSUE TITLE
Notes from meeting w/ Hassan

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/obis2index#2]
frantically typed notes from my brief meeting with Hassan Moustahfid Marine (Ecologist/Manager @ NOAA)

* older paper "Essential Biodiversity Variables" gives foundational definitions
* look at MoF abundance values? or other indicators in MoFs?
* biodiversity indicies in MBON Axiom Portal is missing?
* DEVOTES project, paper, & [DEVOTool](http://www.devotes-project.eu/devotool/) (currently showing error `Error establishing a database connection`)
    * based on work in paper "Catalog of Marine Biodiversity Variables"
* we are not going to get anywhere near to a scientifically valid "biodiversity indicators". The more achievable sub-goals we are aiming for are:
    1. visualize the open data that is available 
    2. identify problems with that data
    3. clean that data
    4. try to do other things to move towards simple indicators like "richness", "shannon diversity", etc
*  this project aims to build up a firm, wide foundation of very simple analyses which are made maximally reproducible and approachable.
* This will enable SDM builders by providing cleaner & easier access to taxa occurrence/abundance data
* we will start off with a small survey/questions/discussion
    * 3 questions maximum
    * do it through slack
* plan for a report out following the workshop:
    * jupyter notebook tutorial-style documentation
    * .md documents for reference-style documentation
    * summarizing blog post 
* day 1 : discussion, repo set up notes, basic data visualization (time series + mapping)
    * divide and conquer: time-series vs mapping. Different spatial regions, different species.
* day 2 : data cleaning? other data views (histograms, ...), 
* beyond: 
    * SDMs for specific indicator species (Hassan's SDMtlb)
    * rarefaction curves (like [this?](https://gist.github.com/jslefche/4f34c8f0d449bb50c27c87f3deacfec5)) to work around sampling bias?

### TODO action items
* Hassan: 
    * google doc to draft questions (will make & share early next week)
    * think about methods to work around sampling bias issue in OBIS data
* Tylar: 
    * reword the ioos/ioos-code-sprint#9 and on the webpage
        * "analysis" -> "visualization"
        * work all the other stuff above in as well

**Comment by hmoustahfid-NOAA** [comment]
I suggest adding "marine" to the title and description. I guess most participants are from the marine community.

**Comment by AbbyBenson** [comment]
I don't think we have to limit to marine since GBIF does exist :-) I'm not in favor of "This will enable SDM builders by providing cleaner & easier access to taxa occurrence/abundance data" as there are already many people providing this already. I agree we will not get to a full analysis and it might just be a visualization but I'm curious to see where we end up anyway and what blockers we run into. Note that there are already R packages and systems that "identify problems with that data" and 
"clean that data". I don't see a need there. Happy to chat more.

**Comment by AbbyBenson** [comment]
Note that I'm more interested in what indicator we CAN develop instead of focusing on what we can't do.

**Comment by AbbyBenson** [comment]
Also worth noting that a visualization CAN be an indicator. It doesn't have to be an analysis strictly speaking to be considered an indicator. Here is an example of a very simple indicator "Growth in Species Occurrence Records Accessible Through GBIF" https://www.bipindicators.net/indicators/growth-in-species-occurrence-records-accessible-through-gbif
